server:
  port: 9000
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:mysql://localhost:3306/yoga1?characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

