package com.yoga.mapper;

import com.yoga.entity.CoachCourse;
import com.yoga.entity.CoachCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoachCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    long countByExample(CoachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByExample(CoachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByPrimaryKey(Integer coachCourseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insert(CoachCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insertSelective(CoachCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    List<CoachCourse> selectByExample(CoachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    CoachCourse selectByPrimaryKey(Integer coachCourseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoachCourse record, @Param("example") CoachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExample(@Param("record") CoachCourse record, @Param("example") CoachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByPrimaryKeySelective(CoachCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_course
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByPrimaryKey(CoachCourse record);
}