package com.yoga.mapper;

import com.yoga.entity.Coach;
import com.yoga.entity.CoachExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CoachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    long countByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insert(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insertSelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    List<Coach> selectByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    Coach selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExampleSelective(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExample(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKeySelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKey(Coach record);

    void updateCoachById(Integer id);
}