package com.yoga.mapper;

import com.yoga.entity.CoachVenuePj;
import com.yoga.entity.CoachVenuePjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoachVenuePjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    long countByExample(CoachVenuePjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int deleteByExample(CoachVenuePjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int deleteByPrimaryKey(Integer pjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int insert(CoachVenuePj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int insertSelective(CoachVenuePj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    List<CoachVenuePj> selectByExample(CoachVenuePjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    CoachVenuePj selectByPrimaryKey(Integer pjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoachVenuePj record, @Param("example") CoachVenuePjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int updateByExample(@Param("record") CoachVenuePj record, @Param("example") CoachVenuePjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int updateByPrimaryKeySelective(CoachVenuePj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_venue_pj
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    int updateByPrimaryKey(CoachVenuePj record);
}