package com.yoga.mapper;

import com.yoga.entity.JobsInfo;
import com.yoga.entity.JobsInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JobsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    long countByExample(JobsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByExample(JobsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByPrimaryKey(Integer jobsInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insert(JobsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insertSelective(JobsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    List<JobsInfo> selectByExample(JobsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    JobsInfo selectByPrimaryKey(Integer jobsInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExampleSelective(@Param("record") JobsInfo record, @Param("example") JobsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExample(@Param("record") JobsInfo record, @Param("example") JobsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKeySelective(JobsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKey(JobsInfo record);

    void updateId(Integer id);
}