package com.yoga.mapper;

import com.yoga.entity.MyFocus;
import com.yoga.entity.MyFocusExample;
import com.yoga.entity.MyFocusKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyFocusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    long countByExample(MyFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int deleteByExample(MyFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int deleteByPrimaryKey(MyFocusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int insert(MyFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int insertSelective(MyFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    List<MyFocus> selectByExample(MyFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    MyFocus selectByPrimaryKey(MyFocusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") MyFocus record, @Param("example") MyFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int updateByExample(@Param("record") MyFocus record, @Param("example") MyFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MyFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_focus
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    int updateByPrimaryKey(MyFocus record);
}