package com.yoga.mapper;

import com.yoga.entity.PurseInOut;
import com.yoga.entity.PurseInOutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurseInOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    long countByExample(PurseInOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByExample(PurseInOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByPrimaryKey(Integer inOutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insert(PurseInOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insertSelective(PurseInOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    List<PurseInOut> selectByExample(PurseInOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    PurseInOut selectByPrimaryKey(Integer inOutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") PurseInOut record, @Param("example") PurseInOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExample(@Param("record") PurseInOut record, @Param("example") PurseInOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByPrimaryKeySelective(PurseInOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_in_out
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByPrimaryKey(PurseInOut record);
}