package com.yoga.mapper;

import com.yoga.entity.RoletreeExample;
import com.yoga.entity.RoletreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    long countByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int deleteByPrimaryKey(RoletreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insert(RoletreeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int insertSelective(RoletreeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    List<RoletreeKey> selectByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoletreeKey record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    int updateByExample(@Param("record") RoletreeKey record, @Param("example") RoletreeExample example);
}