package com.yoga.mapper;

import com.yoga.entity.Coach;
import com.yoga.entity.Venue;
import com.yoga.entity.VenueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VenueMapper {
    //根据场馆查找教练
    List<Coach> findCoachByVenue(Integer uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    long countByExample(VenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByExample(VenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insert(Venue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int insertSelective(Venue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    List<Venue> selectByExample(VenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    Venue selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExampleSelective(@Param("record") Venue record, @Param("example") VenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByExample(@Param("record") Venue record, @Param("example") VenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKeySelective(Venue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    int updateByPrimaryKey(Venue record);

    Venue findById(Integer id);
}