package com.yoga.entity;

import java.util.Date;

public class CoachVenuePj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.pj_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Integer pjId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.pj_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Integer pjUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.pjed_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Integer pjedUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.star
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.time
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Integer bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_venue_pj.bak3
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.pj_id
     *
     * @return the value of coach_venue_pj.pj_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Integer getPjId() {
        return pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.pj_id
     *
     * @param pjId the value for coach_venue_pj.pj_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setPjId(Integer pjId) {
        this.pjId = pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.pj_uid
     *
     * @return the value of coach_venue_pj.pj_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Integer getPjUid() {
        return pjUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.pj_uid
     *
     * @param pjUid the value for coach_venue_pj.pj_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setPjUid(Integer pjUid) {
        this.pjUid = pjUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.pjed_uid
     *
     * @return the value of coach_venue_pj.pjed_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Integer getPjedUid() {
        return pjedUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.pjed_uid
     *
     * @param pjedUid the value for coach_venue_pj.pjed_uid
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setPjedUid(Integer pjedUid) {
        this.pjedUid = pjedUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.star
     *
     * @return the value of coach_venue_pj.star
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.star
     *
     * @param star the value for coach_venue_pj.star
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setStar(String star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.text
     *
     * @return the value of coach_venue_pj.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.text
     *
     * @param text the value for coach_venue_pj.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.image
     *
     * @return the value of coach_venue_pj.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.image
     *
     * @param image the value for coach_venue_pj.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.time
     *
     * @return the value of coach_venue_pj.time
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.time
     *
     * @param time the value for coach_venue_pj.time
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.bak1
     *
     * @return the value of coach_venue_pj.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Integer getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.bak1
     *
     * @param bak1 the value for coach_venue_pj.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setBak1(Integer bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.bak2
     *
     * @return the value of coach_venue_pj.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.bak2
     *
     * @param bak2 the value for coach_venue_pj.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_venue_pj.bak3
     *
     * @return the value of coach_venue_pj.bak3
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_venue_pj.bak3
     *
     * @param bak3 the value for coach_venue_pj.bak3
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3;
    }
}