package com.yoga.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CoachOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public CoachOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCoachOrderIdIsNull() {
            addCriterion("coach_order_id is null");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdIsNotNull() {
            addCriterion("coach_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdEqualTo(String value) {
            addCriterion("coach_order_id =", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdNotEqualTo(String value) {
            addCriterion("coach_order_id <>", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdGreaterThan(String value) {
            addCriterion("coach_order_id >", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("coach_order_id >=", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdLessThan(String value) {
            addCriterion("coach_order_id <", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdLessThanOrEqualTo(String value) {
            addCriterion("coach_order_id <=", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdLike(String value) {
            addCriterion("coach_order_id like", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdNotLike(String value) {
            addCriterion("coach_order_id not like", value, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdIn(List<String> values) {
            addCriterion("coach_order_id in", values, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdNotIn(List<String> values) {
            addCriterion("coach_order_id not in", values, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdBetween(String value1, String value2) {
            addCriterion("coach_order_id between", value1, value2, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andCoachOrderIdNotBetween(String value1, String value2) {
            addCriterion("coach_order_id not between", value1, value2, "coachOrderId");
            return (Criteria) this;
        }

        public Criteria andReqTimeIsNull() {
            addCriterion("req_time is null");
            return (Criteria) this;
        }

        public Criteria andReqTimeIsNotNull() {
            addCriterion("req_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqTimeEqualTo(Date value) {
            addCriterion("req_time =", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeNotEqualTo(Date value) {
            addCriterion("req_time <>", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeGreaterThan(Date value) {
            addCriterion("req_time >", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("req_time >=", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeLessThan(Date value) {
            addCriterion("req_time <", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeLessThanOrEqualTo(Date value) {
            addCriterion("req_time <=", value, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeIn(List<Date> values) {
            addCriterion("req_time in", values, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeNotIn(List<Date> values) {
            addCriterion("req_time not in", values, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeBetween(Date value1, Date value2) {
            addCriterion("req_time between", value1, value2, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqTimeNotBetween(Date value1, Date value2) {
            addCriterion("req_time not between", value1, value2, "reqTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeIsNull() {
            addCriterion("resp_time is null");
            return (Criteria) this;
        }

        public Criteria andRespTimeIsNotNull() {
            addCriterion("resp_time is not null");
            return (Criteria) this;
        }

        public Criteria andRespTimeEqualTo(Date value) {
            addCriterion("resp_time =", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeNotEqualTo(Date value) {
            addCriterion("resp_time <>", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeGreaterThan(Date value) {
            addCriterion("resp_time >", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resp_time >=", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeLessThan(Date value) {
            addCriterion("resp_time <", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeLessThanOrEqualTo(Date value) {
            addCriterion("resp_time <=", value, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeIn(List<Date> values) {
            addCriterion("resp_time in", values, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeNotIn(List<Date> values) {
            addCriterion("resp_time not in", values, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeBetween(Date value1, Date value2) {
            addCriterion("resp_time between", value1, value2, "respTime");
            return (Criteria) this;
        }

        public Criteria andRespTimeNotBetween(Date value1, Date value2) {
            addCriterion("resp_time not between", value1, value2, "respTime");
            return (Criteria) this;
        }

        public Criteria andPayUidIsNull() {
            addCriterion("pay_uid is null");
            return (Criteria) this;
        }

        public Criteria andPayUidIsNotNull() {
            addCriterion("pay_uid is not null");
            return (Criteria) this;
        }

        public Criteria andPayUidEqualTo(Integer value) {
            addCriterion("pay_uid =", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidNotEqualTo(Integer value) {
            addCriterion("pay_uid <>", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidGreaterThan(Integer value) {
            addCriterion("pay_uid >", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_uid >=", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidLessThan(Integer value) {
            addCriterion("pay_uid <", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidLessThanOrEqualTo(Integer value) {
            addCriterion("pay_uid <=", value, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidIn(List<Integer> values) {
            addCriterion("pay_uid in", values, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidNotIn(List<Integer> values) {
            addCriterion("pay_uid not in", values, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidBetween(Integer value1, Integer value2) {
            addCriterion("pay_uid between", value1, value2, "payUid");
            return (Criteria) this;
        }

        public Criteria andPayUidNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_uid not between", value1, value2, "payUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidIsNull() {
            addCriterion("gather_uid is null");
            return (Criteria) this;
        }

        public Criteria andGatherUidIsNotNull() {
            addCriterion("gather_uid is not null");
            return (Criteria) this;
        }

        public Criteria andGatherUidEqualTo(Integer value) {
            addCriterion("gather_uid =", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidNotEqualTo(Integer value) {
            addCriterion("gather_uid <>", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidGreaterThan(Integer value) {
            addCriterion("gather_uid >", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gather_uid >=", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidLessThan(Integer value) {
            addCriterion("gather_uid <", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidLessThanOrEqualTo(Integer value) {
            addCriterion("gather_uid <=", value, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidIn(List<Integer> values) {
            addCriterion("gather_uid in", values, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidNotIn(List<Integer> values) {
            addCriterion("gather_uid not in", values, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidBetween(Integer value1, Integer value2) {
            addCriterion("gather_uid between", value1, value2, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andGatherUidNotBetween(Integer value1, Integer value2) {
            addCriterion("gather_uid not between", value1, value2, "gatherUid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidIsNull() {
            addCriterion("ordercoid is null");
            return (Criteria) this;
        }

        public Criteria andOrdercoidIsNotNull() {
            addCriterion("ordercoid is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercoidEqualTo(Integer value) {
            addCriterion("ordercoid =", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidNotEqualTo(Integer value) {
            addCriterion("ordercoid <>", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidGreaterThan(Integer value) {
            addCriterion("ordercoid >", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordercoid >=", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidLessThan(Integer value) {
            addCriterion("ordercoid <", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidLessThanOrEqualTo(Integer value) {
            addCriterion("ordercoid <=", value, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidIn(List<Integer> values) {
            addCriterion("ordercoid in", values, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidNotIn(List<Integer> values) {
            addCriterion("ordercoid not in", values, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidBetween(Integer value1, Integer value2) {
            addCriterion("ordercoid between", value1, value2, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andOrdercoidNotBetween(Integer value1, Integer value2) {
            addCriterion("ordercoid not between", value1, value2, "ordercoid");
            return (Criteria) this;
        }

        public Criteria andPaycoinIsNull() {
            addCriterion("paycoin is null");
            return (Criteria) this;
        }

        public Criteria andPaycoinIsNotNull() {
            addCriterion("paycoin is not null");
            return (Criteria) this;
        }

        public Criteria andPaycoinEqualTo(Integer value) {
            addCriterion("paycoin =", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinNotEqualTo(Integer value) {
            addCriterion("paycoin <>", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinGreaterThan(Integer value) {
            addCriterion("paycoin >", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("paycoin >=", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinLessThan(Integer value) {
            addCriterion("paycoin <", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinLessThanOrEqualTo(Integer value) {
            addCriterion("paycoin <=", value, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinIn(List<Integer> values) {
            addCriterion("paycoin in", values, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinNotIn(List<Integer> values) {
            addCriterion("paycoin not in", values, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinBetween(Integer value1, Integer value2) {
            addCriterion("paycoin between", value1, value2, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPaycoinNotBetween(Integer value1, Integer value2) {
            addCriterion("paycoin not between", value1, value2, "paycoin");
            return (Criteria) this;
        }

        public Criteria andPayscoreIsNull() {
            addCriterion("payscore is null");
            return (Criteria) this;
        }

        public Criteria andPayscoreIsNotNull() {
            addCriterion("payscore is not null");
            return (Criteria) this;
        }

        public Criteria andPayscoreEqualTo(Integer value) {
            addCriterion("payscore =", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreNotEqualTo(Integer value) {
            addCriterion("payscore <>", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreGreaterThan(Integer value) {
            addCriterion("payscore >", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("payscore >=", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreLessThan(Integer value) {
            addCriterion("payscore <", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreLessThanOrEqualTo(Integer value) {
            addCriterion("payscore <=", value, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreIn(List<Integer> values) {
            addCriterion("payscore in", values, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreNotIn(List<Integer> values) {
            addCriterion("payscore not in", values, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreBetween(Integer value1, Integer value2) {
            addCriterion("payscore between", value1, value2, "payscore");
            return (Criteria) this;
        }

        public Criteria andPayscoreNotBetween(Integer value1, Integer value2) {
            addCriterion("payscore not between", value1, value2, "payscore");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderDescIsNull() {
            addCriterion("order_desc is null");
            return (Criteria) this;
        }

        public Criteria andOrderDescIsNotNull() {
            addCriterion("order_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDescEqualTo(String value) {
            addCriterion("order_desc =", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescNotEqualTo(String value) {
            addCriterion("order_desc <>", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescGreaterThan(String value) {
            addCriterion("order_desc >", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescGreaterThanOrEqualTo(String value) {
            addCriterion("order_desc >=", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescLessThan(String value) {
            addCriterion("order_desc <", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescLessThanOrEqualTo(String value) {
            addCriterion("order_desc <=", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescLike(String value) {
            addCriterion("order_desc like", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescNotLike(String value) {
            addCriterion("order_desc not like", value, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescIn(List<String> values) {
            addCriterion("order_desc in", values, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescNotIn(List<String> values) {
            addCriterion("order_desc not in", values, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescBetween(String value1, String value2) {
            addCriterion("order_desc between", value1, value2, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andOrderDescNotBetween(String value1, String value2) {
            addCriterion("order_desc not between", value1, value2, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andBak1IsNull() {
            addCriterion("bak1 is null");
            return (Criteria) this;
        }

        public Criteria andBak1IsNotNull() {
            addCriterion("bak1 is not null");
            return (Criteria) this;
        }

        public Criteria andBak1EqualTo(Boolean value) {
            addCriterion("bak1 =", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1NotEqualTo(Boolean value) {
            addCriterion("bak1 <>", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1GreaterThan(Boolean value) {
            addCriterion("bak1 >", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1GreaterThanOrEqualTo(Boolean value) {
            addCriterion("bak1 >=", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1LessThan(Boolean value) {
            addCriterion("bak1 <", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1LessThanOrEqualTo(Boolean value) {
            addCriterion("bak1 <=", value, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1In(List<Boolean> values) {
            addCriterion("bak1 in", values, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1NotIn(List<Boolean> values) {
            addCriterion("bak1 not in", values, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1Between(Boolean value1, Boolean value2) {
            addCriterion("bak1 between", value1, value2, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak1NotBetween(Boolean value1, Boolean value2) {
            addCriterion("bak1 not between", value1, value2, "bak1");
            return (Criteria) this;
        }

        public Criteria andBak2IsNull() {
            addCriterion("bak2 is null");
            return (Criteria) this;
        }

        public Criteria andBak2IsNotNull() {
            addCriterion("bak2 is not null");
            return (Criteria) this;
        }

        public Criteria andBak2EqualTo(String value) {
            addCriterion("bak2 =", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2NotEqualTo(String value) {
            addCriterion("bak2 <>", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2GreaterThan(String value) {
            addCriterion("bak2 >", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2GreaterThanOrEqualTo(String value) {
            addCriterion("bak2 >=", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2LessThan(String value) {
            addCriterion("bak2 <", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2LessThanOrEqualTo(String value) {
            addCriterion("bak2 <=", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2Like(String value) {
            addCriterion("bak2 like", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2NotLike(String value) {
            addCriterion("bak2 not like", value, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2In(List<String> values) {
            addCriterion("bak2 in", values, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2NotIn(List<String> values) {
            addCriterion("bak2 not in", values, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2Between(String value1, String value2) {
            addCriterion("bak2 between", value1, value2, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak2NotBetween(String value1, String value2) {
            addCriterion("bak2 not between", value1, value2, "bak2");
            return (Criteria) this;
        }

        public Criteria andBak3IsNull() {
            addCriterion("bak3 is null");
            return (Criteria) this;
        }

        public Criteria andBak3IsNotNull() {
            addCriterion("bak3 is not null");
            return (Criteria) this;
        }

        public Criteria andBak3EqualTo(String value) {
            addCriterion("bak3 =", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3NotEqualTo(String value) {
            addCriterion("bak3 <>", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3GreaterThan(String value) {
            addCriterion("bak3 >", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3GreaterThanOrEqualTo(String value) {
            addCriterion("bak3 >=", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3LessThan(String value) {
            addCriterion("bak3 <", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3LessThanOrEqualTo(String value) {
            addCriterion("bak3 <=", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3Like(String value) {
            addCriterion("bak3 like", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3NotLike(String value) {
            addCriterion("bak3 not like", value, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3In(List<String> values) {
            addCriterion("bak3 in", values, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3NotIn(List<String> values) {
            addCriterion("bak3 not in", values, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3Between(String value1, String value2) {
            addCriterion("bak3 between", value1, value2, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak3NotBetween(String value1, String value2) {
            addCriterion("bak3 not between", value1, value2, "bak3");
            return (Criteria) this;
        }

        public Criteria andBak4IsNull() {
            addCriterion("bak4 is null");
            return (Criteria) this;
        }

        public Criteria andBak4IsNotNull() {
            addCriterion("bak4 is not null");
            return (Criteria) this;
        }

        public Criteria andBak4EqualTo(Integer value) {
            addCriterion("bak4 =", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4NotEqualTo(Integer value) {
            addCriterion("bak4 <>", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4GreaterThan(Integer value) {
            addCriterion("bak4 >", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4GreaterThanOrEqualTo(Integer value) {
            addCriterion("bak4 >=", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4LessThan(Integer value) {
            addCriterion("bak4 <", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4LessThanOrEqualTo(Integer value) {
            addCriterion("bak4 <=", value, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4In(List<Integer> values) {
            addCriterion("bak4 in", values, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4NotIn(List<Integer> values) {
            addCriterion("bak4 not in", values, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4Between(Integer value1, Integer value2) {
            addCriterion("bak4 between", value1, value2, "bak4");
            return (Criteria) this;
        }

        public Criteria andBak4NotBetween(Integer value1, Integer value2) {
            addCriterion("bak4 not between", value1, value2, "bak4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coach_order
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 08 15:16:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coach_order
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}