package com.yoga.entity;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.isreceive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean isreceive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.classfei
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer classfei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.isprivate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean isprivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.isvenue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean isvenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.positive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer positive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.grade
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.certificate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String certificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.flowtypeid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer flowtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.photo
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.uid
     *
     * @return the value of coach.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.uid
     *
     * @param uid the value for coach.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.isreceive
     *
     * @return the value of coach.isreceive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getIsreceive() {
        return isreceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.isreceive
     *
     * @param isreceive the value for coach.isreceive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setIsreceive(Boolean isreceive) {
        this.isreceive = isreceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.classfei
     *
     * @return the value of coach.classfei
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getClassfei() {
        return classfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.classfei
     *
     * @param classfei the value for coach.classfei
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setClassfei(Integer classfei) {
        this.classfei = classfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.isprivate
     *
     * @return the value of coach.isprivate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getIsprivate() {
        return isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.isprivate
     *
     * @param isprivate the value for coach.isprivate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.isvenue
     *
     * @return the value of coach.isvenue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getIsvenue() {
        return isvenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.isvenue
     *
     * @param isvenue the value for coach.isvenue
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setIsvenue(Boolean isvenue) {
        this.isvenue = isvenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.positive
     *
     * @return the value of coach.positive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getPositive() {
        return positive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.positive
     *
     * @param positive the value for coach.positive
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setPositive(Integer positive) {
        this.positive = positive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.grade
     *
     * @return the value of coach.grade
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.grade
     *
     * @param grade the value for coach.grade
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.certificate
     *
     * @return the value of coach.certificate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.certificate
     *
     * @param certificate the value for coach.certificate
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.flowtypeid
     *
     * @return the value of coach.flowtypeid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getFlowtypeid() {
        return flowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.flowtypeid
     *
     * @param flowtypeid the value for coach.flowtypeid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setFlowtypeid(Integer flowtypeid) {
        this.flowtypeid = flowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.photo
     *
     * @return the value of coach.photo
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.photo
     *
     * @param photo the value for coach.photo
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.bak1
     *
     * @return the value of coach.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.bak1
     *
     * @param bak1 the value for coach.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak1(Boolean bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.bak2
     *
     * @return the value of coach.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.bak2
     *
     * @param bak2 the value for coach.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.bak3
     *
     * @return the value of coach.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.bak3
     *
     * @param bak3 the value for coach.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak3(Integer bak3) {
        this.bak3 = bak3;
    }
}