package com.yoga.entity;

public class CoachCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.coach_courseid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer coachCourseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.coach_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer coachUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.coursename
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.cost
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.hour
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_course.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.coach_courseid
     *
     * @return the value of coach_course.coach_courseid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCoachCourseid() {
        return coachCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.coach_courseid
     *
     * @param coachCourseid the value for coach_course.coach_courseid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCoachCourseid(Integer coachCourseid) {
        this.coachCourseid = coachCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.coach_uid
     *
     * @return the value of coach_course.coach_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCoachUid() {
        return coachUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.coach_uid
     *
     * @param coachUid the value for coach_course.coach_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCoachUid(Integer coachUid) {
        this.coachUid = coachUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.coursename
     *
     * @return the value of coach_course.coursename
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.coursename
     *
     * @param coursename the value for coach_course.coursename
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.cost
     *
     * @return the value of coach_course.cost
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.cost
     *
     * @param cost the value for coach_course.cost
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.hour
     *
     * @return the value of coach_course.hour
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.hour
     *
     * @param hour the value for coach_course.hour
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.bak1
     *
     * @return the value of coach_course.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.bak1
     *
     * @param bak1 the value for coach_course.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak1(Integer bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_course.bak2
     *
     * @return the value of coach_course.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_course.bak2
     *
     * @param bak2 the value for coach_course.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }
}