package com.yoga.entity;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String countryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryid
     *
     * @return the value of country.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryid
     *
     * @param countryid the value for country.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryname
     *
     * @return the value of country.countryname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryname
     *
     * @param countryname the value for country.countryname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }
}