package com.yoga.entity;

import java.util.Date;

public class FriendReq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.req_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer reqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.req_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer reqUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.receive_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer receiveUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.req_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date reqTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.resp_msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String respMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.resp_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date respTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.result
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Boolean result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.isread
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Boolean isread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Boolean bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_req.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.req_id
     *
     * @return the value of friend_req.req_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.req_id
     *
     * @param reqId the value for friend_req.req_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setReqId(Integer reqId) {
        this.reqId = reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.req_uid
     *
     * @return the value of friend_req.req_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getReqUid() {
        return reqUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.req_uid
     *
     * @param reqUid the value for friend_req.req_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setReqUid(Integer reqUid) {
        this.reqUid = reqUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.receive_uid
     *
     * @return the value of friend_req.receive_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getReceiveUid() {
        return receiveUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.receive_uid
     *
     * @param receiveUid the value for friend_req.receive_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setReceiveUid(Integer receiveUid) {
        this.receiveUid = receiveUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.req_time
     *
     * @return the value of friend_req.req_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.req_time
     *
     * @param reqTime the value for friend_req.req_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.msg
     *
     * @return the value of friend_req.msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.msg
     *
     * @param msg the value for friend_req.msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.resp_msg
     *
     * @return the value of friend_req.resp_msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.resp_msg
     *
     * @param respMsg the value for friend_req.resp_msg
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.resp_time
     *
     * @return the value of friend_req.resp_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getRespTime() {
        return respTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.resp_time
     *
     * @param respTime the value for friend_req.resp_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setRespTime(Date respTime) {
        this.respTime = respTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.result
     *
     * @return the value of friend_req.result
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.result
     *
     * @param result the value for friend_req.result
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.isread
     *
     * @return the value of friend_req.isread
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.isread
     *
     * @param isread the value for friend_req.isread
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.bak1
     *
     * @return the value of friend_req.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Boolean getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.bak1
     *
     * @param bak1 the value for friend_req.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak1(Boolean bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_req.bak2
     *
     * @return the value of friend_req.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_req.bak2
     *
     * @param bak2 the value for friend_req.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }
}