package com.yoga.entity;

public class HomeShow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.show_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Integer showId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.isdelete
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private String bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_show.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    private Boolean bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.show_id
     *
     * @return the value of home_show.show_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Integer getShowId() {
        return showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.show_id
     *
     * @param showId the value for home_show.show_id
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setShowId(Integer showId) {
        this.showId = showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.image
     *
     * @return the value of home_show.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.image
     *
     * @param image the value for home_show.image
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.text
     *
     * @return the value of home_show.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.text
     *
     * @param text the value for home_show.text
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.isdelete
     *
     * @return the value of home_show.isdelete
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.isdelete
     *
     * @param isdelete the value for home_show.isdelete
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.bak1
     *
     * @return the value of home_show.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.bak1
     *
     * @param bak1 the value for home_show.bak1
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_show.bak2
     *
     * @return the value of home_show.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public Boolean getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_show.bak2
     *
     * @param bak2 the value for home_show.bak2
     *
     * @mbg.generated Mon Jun 08 15:25:25 CST 2020
     */
    public void setBak2(Boolean bak2) {
        this.bak2 = bak2;
    }
}