package com.yoga.entity;

import java.util.Date;

public class MyFocus extends MyFocusKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_focus.focus_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date focusTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_focus.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_focus.focus_time
     *
     * @return the value of my_focus.focus_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getFocusTime() {
        return focusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_focus.focus_time
     *
     * @param focusTime the value for my_focus.focus_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setFocusTime(Date focusTime) {
        this.focusTime = focusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_focus.bak1
     *
     * @return the value of my_focus.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_focus.bak1
     *
     * @param bak1 the value for my_focus.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1;
    }
}