package com.yoga.entity;

public class MyfriendKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfriend.myid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer myid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfriend.toid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer toid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfriend.myid
     *
     * @return the value of myfriend.myid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfriend.myid
     *
     * @param myid the value for myfriend.myid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setMyid(Integer myid) {
        this.myid = myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfriend.toid
     *
     * @return the value of myfriend.toid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfriend.toid
     *
     * @param toid the value for myfriend.toid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setToid(Integer toid) {
        this.toid = toid;
    }
}