package com.yoga.entity;

import java.util.List;

public class Province {
    private List citys;
    private Country country;



    public List getCitys() {
        return citys;
    }

    public void setCitys(List citys) {
        this.citys = citys;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pcode
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private String pcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pid
     *
     * @return the value of province.pid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pid
     *
     * @param pid the value for province.pid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.countryid
     *
     * @return the value of province.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.countryid
     *
     * @param countryid the value for province.countryid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pcode
     *
     * @return the value of province.pcode
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pcode
     *
     * @param pcode the value for province.pcode
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

}