package com.yoga.entity;

public class Purse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.purseid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer purseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.uid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.coin
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer coin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.paypass
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private String paypass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.typeid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.cash
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer cash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.status
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.bak3
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private String bak3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purse.score
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.purseid
     *
     * @return the value of purse.purseid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getPurseid() {
        return purseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.purseid
     *
     * @param purseid the value for purse.purseid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setPurseid(Integer purseid) {
        this.purseid = purseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.uid
     *
     * @return the value of purse.uid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.uid
     *
     * @param uid the value for purse.uid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.coin
     *
     * @return the value of purse.coin
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.coin
     *
     * @param coin the value for purse.coin
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.paypass
     *
     * @return the value of purse.paypass
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public String getPaypass() {
        return paypass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.paypass
     *
     * @param paypass the value for purse.paypass
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setPaypass(String paypass) {
        this.paypass = paypass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.typeid
     *
     * @return the value of purse.typeid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.typeid
     *
     * @param typeid the value for purse.typeid
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.cash
     *
     * @return the value of purse.cash
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.cash
     *
     * @param cash the value for purse.cash
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setCash(Integer cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.status
     *
     * @return the value of purse.status
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.status
     *
     * @param status the value for purse.status
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.bak3
     *
     * @return the value of purse.bak3
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.bak3
     *
     * @param bak3 the value for purse.bak3
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purse.score
     *
     * @return the value of purse.score
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purse.score
     *
     * @param score the value for purse.score
     *
     * @mbg.generated Thu Jun 11 14:45:49 GMT+08:00 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}