package com.yoga.entity;

import java.util.ArrayList;
import java.util.List;

public class VenueCoachExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public VenueCoachExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVenueidIsNull() {
            addCriterion("venueid is null");
            return (Criteria) this;
        }

        public Criteria andVenueidIsNotNull() {
            addCriterion("venueid is not null");
            return (Criteria) this;
        }

        public Criteria andVenueidEqualTo(Integer value) {
            addCriterion("venueid =", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidNotEqualTo(Integer value) {
            addCriterion("venueid <>", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidGreaterThan(Integer value) {
            addCriterion("venueid >", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidGreaterThanOrEqualTo(Integer value) {
            addCriterion("venueid >=", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidLessThan(Integer value) {
            addCriterion("venueid <", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidLessThanOrEqualTo(Integer value) {
            addCriterion("venueid <=", value, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidIn(List<Integer> values) {
            addCriterion("venueid in", values, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidNotIn(List<Integer> values) {
            addCriterion("venueid not in", values, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidBetween(Integer value1, Integer value2) {
            addCriterion("venueid between", value1, value2, "venueid");
            return (Criteria) this;
        }

        public Criteria andVenueidNotBetween(Integer value1, Integer value2) {
            addCriterion("venueid not between", value1, value2, "venueid");
            return (Criteria) this;
        }

        public Criteria andCoachidIsNull() {
            addCriterion("coachid is null");
            return (Criteria) this;
        }

        public Criteria andCoachidIsNotNull() {
            addCriterion("coachid is not null");
            return (Criteria) this;
        }

        public Criteria andCoachidEqualTo(Integer value) {
            addCriterion("coachid =", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidNotEqualTo(Integer value) {
            addCriterion("coachid <>", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidGreaterThan(Integer value) {
            addCriterion("coachid >", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidGreaterThanOrEqualTo(Integer value) {
            addCriterion("coachid >=", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidLessThan(Integer value) {
            addCriterion("coachid <", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidLessThanOrEqualTo(Integer value) {
            addCriterion("coachid <=", value, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidIn(List<Integer> values) {
            addCriterion("coachid in", values, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidNotIn(List<Integer> values) {
            addCriterion("coachid not in", values, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidBetween(Integer value1, Integer value2) {
            addCriterion("coachid between", value1, value2, "coachid");
            return (Criteria) this;
        }

        public Criteria andCoachidNotBetween(Integer value1, Integer value2) {
            addCriterion("coachid not between", value1, value2, "coachid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venue_coach
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table venue_coach
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}