package com.yoga.entity;

public class VenueCoachKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue_coach.venueid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private Integer venueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue_coach.coachid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    private Integer coachid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue_coach.venueid
     *
     * @return the value of venue_coach.venueid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public Integer getVenueid() {
        return venueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue_coach.venueid
     *
     * @param venueid the value for venue_coach.venueid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setVenueid(Integer venueid) {
        this.venueid = venueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue_coach.coachid
     *
     * @return the value of venue_coach.coachid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public Integer getCoachid() {
        return coachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue_coach.coachid
     *
     * @param coachid the value for venue_coach.coachid
     *
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
     */
    public void setCoachid(Integer coachid) {
        this.coachid = coachid;
    }
}