package com.yoga.entity;

import java.util.List;

public class Venue {

    private Userinfo userinfo;
    private JobsInfo jobsInfo;
    private List<JobsInfo> jobsInfos;
    private Coach coach;
    private List<Coach> coachs;

    public Userinfo getUserinfo() {
        return userinfo;
    }

    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.venuename
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String venuename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.tel
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.mobile
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.address
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.licence
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String licence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.ischeck
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean ischeck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Boolean bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private Integer bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String bak3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venue.bak4
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    private String bak4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.uid
     *
     * @return the value of venue.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.uid
     *
     * @param uid the value for venue.uid
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.venuename
     *
     * @return the value of venue.venuename
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getVenuename() {
        return venuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.venuename
     *
     * @param venuename the value for venue.venuename
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setVenuename(String venuename) {
        this.venuename = venuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.tel
     *
     * @return the value of venue.tel
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.tel
     *
     * @param tel the value for venue.tel
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.mobile
     *
     * @return the value of venue.mobile
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.mobile
     *
     * @param mobile the value for venue.mobile
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.address
     *
     * @return the value of venue.address
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.address
     *
     * @param address the value for venue.address
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.info
     *
     * @return the value of venue.info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.info
     *
     * @param info the value for venue.info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.licence
     *
     * @return the value of venue.licence
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getLicence() {
        return licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.licence
     *
     * @param licence the value for venue.licence
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setLicence(String licence) {
        this.licence = licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.ischeck
     *
     * @return the value of venue.ischeck
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.ischeck
     *
     * @param ischeck the value for venue.ischeck
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setIscheck(Boolean ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.bak1
     *
     * @return the value of venue.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Boolean getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.bak1
     *
     * @param bak1 the value for venue.bak1
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak1(Boolean bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.bak2
     *
     * @return the value of venue.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public Integer getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.bak2
     *
     * @param bak2 the value for venue.bak2
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak2(Integer bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.bak3
     *
     * @return the value of venue.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.bak3
     *
     * @param bak3 the value for venue.bak3
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venue.bak4
     *
     * @return the value of venue.bak4
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public String getBak4() {
        return bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venue.bak4
     *
     * @param bak4 the value for venue.bak4
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jun 09 20:15:58 GMT+08:00 2020
=======
     * @mbg.generated Tue Jun 09 19:38:04 CST 2020
>>>>>>> 3113bc6... 场馆
     */
    public void setBak4(String bak4) {
        this.bak4 = bak4;
    }

    public JobsInfo getJobsInfo() {
        return jobsInfo;
    }

    public void setJobsInfo(JobsInfo jobsInfo) {
        this.jobsInfo = jobsInfo;
    }

    public List<JobsInfo> getJobsInfos() {
        return jobsInfos;
    }

    public void setJobsInfos(List<JobsInfo> jobsInfos) {
        this.jobsInfos = jobsInfos;
    }

    public Coach getCoach() {
        return coach;
    }

    public void setCoach(Coach coach) {
        this.coach = coach;
    }

    public List<Coach> getCoachs() {
        return coachs;
    }

    public void setCoachs(List<Coach> coachs) {
        this.coachs = coachs;
    }
}