package com.yoga.entity;

import java.util.Date;

public class Vip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.card_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.owner
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.card_type
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.card_grade
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer cardGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.card_code
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String cardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.starttime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.endtime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.use_count
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer useCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.bak3
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.card_id
     *
     * @return the value of vip.card_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.card_id
     *
     * @param cardId the value for vip.card_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.owner
     *
     * @return the value of vip.owner
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.owner
     *
     * @param owner the value for vip.owner
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.card_type
     *
     * @return the value of vip.card_type
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.card_type
     *
     * @param cardType the value for vip.card_type
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.card_grade
     *
     * @return the value of vip.card_grade
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCardGrade() {
        return cardGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.card_grade
     *
     * @param cardGrade the value for vip.card_grade
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCardGrade(Integer cardGrade) {
        this.cardGrade = cardGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.card_code
     *
     * @return the value of vip.card_code
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.card_code
     *
     * @param cardCode the value for vip.card_code
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.starttime
     *
     * @return the value of vip.starttime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.starttime
     *
     * @param starttime the value for vip.starttime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.endtime
     *
     * @return the value of vip.endtime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.endtime
     *
     * @param endtime the value for vip.endtime
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.use_count
     *
     * @return the value of vip.use_count
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.use_count
     *
     * @param useCount the value for vip.use_count
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.isdelete
     *
     * @return the value of vip.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.isdelete
     *
     * @param isdelete the value for vip.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.bak1
     *
     * @return the value of vip.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.bak1
     *
     * @param bak1 the value for vip.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak1(Integer bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.bak2
     *
     * @return the value of vip.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.bak2
     *
     * @param bak2 the value for vip.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.bak3
     *
     * @return the value of vip.bak3
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.bak3
     *
     * @param bak3 the value for vip.bak3
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3;
    }
}