package com.yoga.entity;

public class VipGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_grade.grade_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Integer gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_grade.grade_name
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private String gradeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_grade.grade_id
     *
     * @return the value of vip_grade.grade_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_grade.grade_id
     *
     * @param gradeId the value for vip_grade.grade_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_grade.grade_name
     *
     * @return the value of vip_grade.grade_name
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_grade.grade_name
     *
     * @param gradeName the value for vip_grade.grade_name
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }
}