package com.yoga.entity;

public class VipType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_type.type_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_type.type_name
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_type.discount
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_type.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_type.type_id
     *
     * @return the value of vip_type.type_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_type.type_id
     *
     * @param typeId the value for vip_type.type_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_type.type_name
     *
     * @return the value of vip_type.type_name
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_type.type_name
     *
     * @param typeName the value for vip_type.type_name
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_type.discount
     *
     * @return the value of vip_type.discount
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_type.discount
     *
     * @param discount the value for vip_type.discount
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_type.isdelete
     *
     * @return the value of vip_type.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_type.isdelete
     *
     * @param isdelete the value for vip_type.isdelete
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}