package com.yoga.entity;

import java.util.Date;

public class YogaCircle {
    private Userinfo userinfo;

    public Userinfo getUserinfo() {
        return userinfo;
    }

    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.yoga_circle_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Integer yogaCircleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.circle_uid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Integer circleUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.circle_time
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Date circleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.text
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.bak1
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Integer bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yoga_circle.bak2
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private Integer bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.yoga_circle_id
     *
     * @return the value of yoga_circle.yoga_circle_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Integer getYogaCircleId() {
        return yogaCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.yoga_circle_id
     *
     * @param yogaCircleId the value for yoga_circle.yoga_circle_id
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setYogaCircleId(Integer yogaCircleId) {
        this.yogaCircleId = yogaCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.circle_uid
     *
     * @return the value of yoga_circle.circle_uid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Integer getCircleUid() {
        return circleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.circle_uid
     *
     * @param circleUid the value for yoga_circle.circle_uid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setCircleUid(Integer circleUid) {
        this.circleUid = circleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.circle_time
     *
     * @return the value of yoga_circle.circle_time
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Date getCircleTime() {
        return circleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.circle_time
     *
     * @param circleTime the value for yoga_circle.circle_time
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setCircleTime(Date circleTime) {
        this.circleTime = circleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.text
     *
     * @return the value of yoga_circle.text
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.text
     *
     * @param text the value for yoga_circle.text
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.bak1
     *
     * @return the value of yoga_circle.bak1
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Integer getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.bak1
     *
     * @param bak1 the value for yoga_circle.bak1
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setBak1(Integer bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yoga_circle.bak2
     *
     * @return the value of yoga_circle.bak2
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public Integer getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yoga_circle.bak2
     *
     * @param bak2 the value for yoga_circle.bak2
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setBak2(Integer bak2) {
        this.bak2 = bak2;
    }
}