package com.yoga.entity;

import java.util.Date;

public class Zan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.zan_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer zanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.circle_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer circleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.zan_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer zanUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.zan_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Date zanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private Integer bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.zan_id
     *
     * @return the value of zan.zan_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getZanId() {
        return zanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.zan_id
     *
     * @param zanId the value for zan.zan_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setZanId(Integer zanId) {
        this.zanId = zanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.circle_id
     *
     * @return the value of zan.circle_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.circle_id
     *
     * @param circleId the value for zan.circle_id
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setCircleId(Integer circleId) {
        this.circleId = circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.zan_uid
     *
     * @return the value of zan.zan_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getZanUid() {
        return zanUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.zan_uid
     *
     * @param zanUid the value for zan.zan_uid
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setZanUid(Integer zanUid) {
        this.zanUid = zanUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.zan_time
     *
     * @return the value of zan.zan_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Date getZanTime() {
        return zanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.zan_time
     *
     * @param zanTime the value for zan.zan_time
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setZanTime(Date zanTime) {
        this.zanTime = zanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.bak1
     *
     * @return the value of zan.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public Integer getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.bak1
     *
     * @param bak1 the value for zan.bak1
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak1(Integer bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.bak2
     *
     * @return the value of zan.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.bak2
     *
     * @param bak2 the value for zan.bak2
     *
     * @mbg.generated Mon Jun 08 15:16:38 CST 2020
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }
}