package com.yoga.entity;

public class Zone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private String zid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zname
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private String zname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.cid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zid
     *
     * @return the value of zone.zid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public String getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zid
     *
     * @param zid the value for zone.zid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setZid(String zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zname
     *
     * @return the value of zone.zname
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public String getZname() {
        return zname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zname
     *
     * @param zname the value for zone.zname
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setZname(String zname) {
        this.zname = zname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.cid
     *
     * @return the value of zone.cid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.cid
     *
     * @param cid the value for zone.cid
     *
     * @mbg.generated Tue Jun 09 19:11:09 GMT+08:00 2020
     */
    public void setCid(String cid) {
        this.cid = cid;
    }
}